name: ${name}
main: com.aleksey.castlegates.CastleGates
version: ${version}
author: Aleksey-Terzi
api-version: 1.18
description: 'Drawable gates and bridges'
softdepend: [NameLayer, Citadel, Bastion]
commands:
  cg:
    description: Manage Castle Gates.
    usage: |
           /<command> normal - Normal mode
           /<command> create - Create gear block mode
           /<command> link - Link gears mode
           /<command> timer [<period in seconds> [<draw | undraw | revert>]] [door] - Set timer mode
           /<command> info - Information mode
  gear:
    description: Create gear block mode
  link:
    description: Create link block mode